apiVersion: v1
kind: Service
metadata:
  name: sftpgo
spec:
  selector:
    app: sftpgo
  ports:
  - name: sftp
    port: 2022
    targetPort: 2022
  - name: http
    port: 8080
    targetPort: 8080
  type: LoadBalancer # Use LoadBalancer to create an AWS NLB